# Generated by Django 5.0.3 on 2024-03-31 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_description_en_course_info_en_course_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description_en'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Name_en'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_id', models.IntegerField()),
                ('is_seen', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.comment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
