# Generated by Django 5.0.3 on 2024-04-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_notification_lesson_id_notification_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
